import type { Metadata } from "next";
import { Inter, Montserrat, Prompt } from "next/font/google";
// import "../../../src/app/globals.css";
import classNames from "classnames";
import seenpic from "../../../img/image 7.png";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prompt",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const prompt = Prompt({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prompt",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Customer Service",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();

  return (
    <>
      <Sidebar />
      <main className="flex flex-grow bg-white w-full h-full overflow-hidden">
        {children}
      </main>
    </>
  );
}
