import type { Metadata } from "next";
import "./globals.css";
import classNames from "classnames";

export const metadata: Metadata = {
  title: "Customer Service",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(`h-screen max-w-screen flex flex-1`)}>
        {children}
      </body>
    </html>
  );
}
